#if UNITY_EDITOR
using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;using UnityEditor.Build.Reporting;using UnityEngine.Rendering;using UnityEngine.Rendering.Universal;
namespace CorruptStateRP.Editor {
public static class BuildProject {
 [MenuItem("Corrupt State RP/Generate Onboarding Scenes")]
 public static void GenerateOnboardingScenes(){ConfigureProjectSettings();EnsureURP();SyncDataResources();Generate3DPrefabs();System.IO.Directory.CreateDirectory("Assets/Scenes");Make("SplashScreenScene",CorruptStateRP.Onboarding.OnboardingScreen.Mode.Splash);Make("LoginScene",CorruptStateRP.Onboarding.OnboardingScreen.Mode.Login);Make("LobbyScene",CorruptStateRP.Onboarding.OnboardingScreen.Mode.Lobby);Make("CityRPScene",null);EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene("Assets/Scenes/SplashScreenScene.unity",true),new EditorBuildSettingsScene("Assets/Scenes/LoginScene.unity",true),new EditorBuildSettingsScene("Assets/Scenes/LobbyScene.unity",true),new EditorBuildSettingsScene("Assets/Scenes/CityRPScene.unity",true)};AssetDatabase.SaveAssets();}
 static void ConfigureProjectSettings(){PlayerSettings.companyName="Corrupt State Studio";PlayerSettings.productName="Corrupt State RP";PlayerSettings.bundleVersion="0.1.0";PlayerSettings.defaultInterfaceOrientation=UIOrientation.LandscapeLeft;PlayerSettings.allowedAutorotateToPortrait=false;PlayerSettings.allowedAutorotateToPortraitUpsideDown=false;PlayerSettings.allowedAutorotateToLandscapeRight=false;PlayerSettings.allowedAutorotateToLandscapeLeft=true;PlayerSettings.SetApplicationIdentifier(BuildTargetGroup.Android,"com.corruptstate.rp");PlayerSettings.SetScriptingBackend(BuildTargetGroup.Android,ScriptingImplementation.IL2CPP);PlayerSettings.SetApiCompatibilityLevel(BuildTargetGroup.Android,ApiCompatibilityLevel.NET_Standard);PlayerSettings.Android.minSdkVersion=AndroidSdkVersions.AndroidApiLevel26;PlayerSettings.Android.targetSdkVersion=AndroidSdkVersions.AndroidApiLevel35;PlayerSettings.Android.targetArchitectures=AndroidArchitecture.ARM64|AndroidArchitecture.ARMv7;PlayerSettings.Android.androidIsGame=true;EditorUserBuildSettings.buildAppBundle=true;PlayerSettings.Android.useCustomKeystore=true;var ks=System.Environment.GetEnvironmentVariable("ANDROID_KEYSTORE_PATH");var kp=System.Environment.GetEnvironmentVariable("ANDROID_KEYSTORE_PASSWORD");var alias=System.Environment.GetEnvironmentVariable("ANDROID_KEY_ALIAS");var ap=System.Environment.GetEnvironmentVariable("ANDROID_KEY_PASSWORD");if(string.IsNullOrEmpty(ks)||string.IsNullOrEmpty(kp)||string.IsNullOrEmpty(alias)||string.IsNullOrEmpty(ap))throw new System.Exception("Android signing environment is missing.");PlayerSettings.Android.keystoreName=ks;PlayerSettings.Android.keystorePass=kp;PlayerSettings.Android.keyaliasName=alias;PlayerSettings.Android.keyaliasPass=ap;}
 static void EnsureURP(){const string path="Assets/Settings/CorruptStateURP.asset";System.IO.Directory.CreateDirectory("Assets/Settings");var pipeline=AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(path);if(pipeline==null){pipeline=ScriptableObject.CreateInstance<UniversalRenderPipelineAsset>();AssetDatabase.CreateAsset(pipeline,path);}GraphicsSettings.defaultRenderPipeline=pipeline;QualitySettings.renderPipeline=pipeline;AssetDatabase.SaveAssets();}
 static void SyncDataResources(){System.IO.Directory.CreateDirectory("Assets/Resources/Data");foreach(var name in new[]{"factions.json","jobs.json","streets.json"}){var source="Assets/Data/"+name;var target="Assets/Resources/Data/"+name;if(!System.IO.File.Exists(source))throw new System.Exception("Required data file missing: "+source);System.IO.File.Copy(source,target,true);}AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);}
 static void Generate3DPrefabs(){AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);var dir="Assets/Resources/Generated3D";System.IO.Directory.CreateDirectory(dir);string[] models={"Assets/Resources/External/city/commercial_a.glb","Assets/Resources/External/city/commercial_b.glb","Assets/Resources/External/city/skyscraper_a.glb","Assets/Resources/External/city/skyscraper_b.glb","Assets/Resources/External/city/skyscraper_c.glb","Assets/Resources/External/city/suburban_a.glb","Assets/Resources/External/city/suburban_b.glb","Assets/Resources/External/city/suburban_c.glb","Assets/Resources/External/vehicles/sedan.glb","Assets/Resources/External/vehicles/suv.glb","Assets/Resources/External/vehicles/taxi.glb","Assets/Resources/External/vehicles/police.glb","Assets/Resources/External/character/citizen.glb"};foreach(var model in models){var source=AssetDatabase.LoadAssetAtPath<GameObject>(model);if(source==null){Debug.LogWarning("3D model not imported: "+model);continue;}var name=System.IO.Path.GetFileNameWithoutExtension(model);var instance=Object.Instantiate(source);instance.name=name;PrefabUtility.SaveAsPrefabAsset(instance,dir+"/"+name+".prefab");Object.DestroyImmediate(instance);}AssetDatabase.SaveAssets();AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);}
 static void Make(string name,CorruptStateRP.Onboarding.OnboardingScreen.Mode? mode){var s=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);if(mode.HasValue){var go=new GameObject("OnboardingScreen");var c=go.AddComponent<CorruptStateRP.Onboarding.OnboardingScreen>();var so=new SerializedObject(c);so.FindProperty("mode").enumValueIndex=(int)mode.Value;so.ApplyModifiedPropertiesWithoutUndo();if(mode.Value==CorruptStateRP.Onboarding.OnboardingScreen.Mode.Lobby)go.AddComponent<CorruptStateRP.Lobby.LobbyScreen>();if(mode.Value==CorruptStateRP.Onboarding.OnboardingScreen.Mode.Splash){new GameObject("AuthClient").AddComponent<CorruptStateRP.Auth.AuthClient>();go.AddComponent<CorruptStateRP.Onboarding.OnboardingFlowController>();}}else{var gm=new GameObject("GameManager");gm.AddComponent<CorruptStateRP.GameManager>();gm.AddComponent<CorruptStateRP.CityInteractionSystem>();gm.AddComponent<CorruptStateRP.FactionDashboard>();gm.AddComponent<CorruptStateRP.AdminDashboard>();gm.AddComponent<CorruptStateRP.AdminPanelController>();gm.AddComponent<CorruptStateRP.FactionLeaderUI>();var mobile=new GameObject("MobileHUD");mobile.AddComponent<CorruptStateRP.Mobile.MobileHUD>();var citizen=new GameObject("NewCitizenProgram");citizen.AddComponent<CorruptStateRP.Citizens.NewCitizenProgram>();}EditorSceneManager.SaveScene(s,"Assets/Scenes/"+name+".unity");}
 [MenuItem("Corrupt State RP/Build Android")]
 public static void BuildAndroid(){GenerateOnboardingScenes();var o=new BuildPlayerOptions{scenes=new[]{"Assets/Scenes/SplashScreenScene.unity","Assets/Scenes/LoginScene.unity","Assets/Scenes/LobbyScene.unity","Assets/Scenes/CityRPScene.unity"},locationPathName="Builds/Android/CorruptStateRP.aab",target=BuildTarget.Android,options=BuildOptions.None};var r=BuildPipeline.BuildPlayer(o);if(r.summary.result!=BuildResult.Succeeded)throw new System.Exception("Android AAB build failed: "+r.summary.result);}
}}
#endif