using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using CorruptStateRP.UI;
using CorruptStateRP.Citizens;
namespace CorruptStateRP.Lobby {
public sealed class LobbyScreen:MonoBehaviour {
 Font font; RectTransform content; NewCitizenProgram citizenProgram; GameObject shopPanel;
 void Awake(){font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");var cp=new GameObject("NewCitizenProgram");citizenProgram=cp.AddComponent<NewCitizenProgram>();Build();}
 void Build(){var canvas=new GameObject("LobbyCanvas").AddComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;canvas.gameObject.AddComponent<CanvasScaler>();canvas.gameObject.AddComponent<GraphicRaycaster>();canvas.gameObject.AddComponent<ResponsiveCanvas>();var safe=new GameObject("SafeArea",typeof(RectTransform),typeof(SafeAreaPanel));safe.transform.SetParent(canvas.transform,false);var s=safe.GetComponent<RectTransform>();s.anchorMin=Vector2.zero;s.anchorMax=Vector2.one;s.offsetMin=s.offsetMax=Vector2.zero;safe.AddComponent<Image>().color=new Color(.018f,.02f,.027f,1);content=Panel(safe.transform,new Color(.025f,.03f,.04f,.96f));Anchor(content,.035f,.045f,.965f,.955f);Text(content,"CORRUPT STATE RP",30,TextAnchor.UpperLeft,new Vector2(28,-24),new Vector2(520,48));Text(content,"اللوبي",28,TextAnchor.UpperRight,new Vector2(-28,-24),new Vector2(260,48));var profile=Panel(content,new Color(.07f,.075f,.09f,1));Anchor(profile,.035f,.67f,.965f,.94f);Text(profile,"المواطن الجديد",26,TextAnchor.UpperRight,new Vector2(-24,-18),new Vector2(360,42));Text(profile,"Level 1",22,TextAnchor.UpperRight,new Vector2(-24,-62),new Vector2(220,36));Text(profile,"XP 0 / 1000",20,TextAnchor.UpperRight,new Vector2(-24,-100),new Vector2(250,34));Text(profile,"الرصيد $0",22,TextAnchor.UpperLeft,new Vector2(24,-62),new Vector2(300,36));Text(profile,"الحالة: New Citizen",18,TextAnchor.UpperLeft,new Vector2(24,-102),new Vector2(330,34));var missions=Panel(content,new Color(.055f,.06f,.075f,1));Anchor(missions,.035f,.28f,.635f,.64f);Text(missions,"المهام اليومية",24,TextAnchor.UpperRight,new Vector2(-20,-16),new Vector2(300,40));Mission(missions,"إكمال مهمة مواطن","+ مكافأة من الخادم",-64);Mission(missions,"زيارة البنك","مكافأة من الخادم",-126);Mission(missions,"التعرف على 5 مواطنين","مكافأة من الخادم",-188);var factions=Panel(content,new Color(.055f,.06f,.075f,1));Anchor(factions,.665f,.28f,.965f,.64f);Text(factions,"الفصائل",24,TextAnchor.UpperRight,new Vector2(-20,-16),new Vector2(250,40));Text(factions,"الشرطة • الجيش • الطب\nالدفاع المدني • القضاء\nالحكومة • الأمن الوطني • العصابات",18,TextAnchor.UpperRight,new Vector2(-20,-70),new Vector2(330,150));Button(content,"المتجر والعروض",()=>ToggleShop(),new Vector2(.035f,.12f),new Vector2(.28f,.23f));Button(content,"برنامج المواطنين",()=>citizenProgram.Show(),new Vector2(.30f,.12f),new Vector2(.545f,.23f));Button(content,"دخول المدينة",()=>SceneManager.LoadScene("CityRPScene"),new Vector2(.565f,.12f),new Vector2(.965f,.23f));}
 void ToggleShop(){if(shopPanel==null){shopPanel=new GameObject("ShopPanel");shopPanel.transform.SetParent(content,false);Anchor(shopPanel.AddComponent<RectTransform>(),.10f,.20f,.90f,.80f);shopPanel.AddComponent<Image>().color=new Color(.025f,.03f,.04f,.99f);Text(shopPanel.transform,"المتجر والعروض",28,TextAnchor.UpperRight,new Vector2(-24,-24),new Vector2(-40,50));Text(shopPanel.transform,"المتجر غير متصل بالاقتصاد حتى تفعيل أحداث الخادم.",20,TextAnchor.UpperRight,new Vector2(-30,-95),new Vector2(-50,300));Button(shopPanel.transform,"إغلاق",()=>shopPanel.SetActive(false),new Vector2(.68f,.05f),new Vector2(.94f,.14f));}shopPanel.SetActive(true);}
 void Mission(Transform p,string title,string reward,float y){Text(p,title,18,TextAnchor.UpperRight,new Vector2(-20,y),new Vector2(-30,32));Text(p,reward,15,TextAnchor.UpperLeft,new Vector2(20,y),new Vector2(230,32));}
 RectTransform Panel(Transform p,Color c){var g=new GameObject("Panel");g.transform.SetParent(p,false);var r=g.AddComponent<RectTransform>();g.AddComponent<Image>().color=c;return r;}
 void Anchor(RectTransform r,float a,float b,float c,float d){r.anchorMin=new Vector2(a,b);r.anchorMax=new Vector2(c,d);r.offsetMin=r.offsetMax=Vector2.zero;}
 Text Text(Transform p,string v,int n,TextAnchor a,Vector2 pos,Vector2 size){var g=new GameObject("Text");g.transform.SetParent(p,false);var t=g.AddComponent<Text>();t.font=font;t.text=ArabicFixer.Fix(v);t.fontSize=n;t.alignment=a;t.color=Color.white;t.horizontalOverflow=HorizontalWrapMode.Wrap;t.verticalOverflow=VerticalWrapMode.Overflow;var r=t.rectTransform;r.anchorMin=r.anchorMax=new Vector2(.5f,.5f);r.anchoredPosition=pos;r.sizeDelta=size;return t;}
 void Button(Transform p,string v,UnityEngine.Events.UnityAction a,Vector2 min,Vector2 max){var g=new GameObject(v);g.transform.SetParent(p,false);var r=g.AddComponent<RectTransform>();r.anchorMin=min;r.anchorMax=max;r.offsetMin=r.offsetMax=Vector2.zero;var i=g.AddComponent<Image>();i.color=new Color(.55f,.045f,.06f,1);var b=g.AddComponent<Button>();b.targetGraphic=i;b.onClick.AddListener(a);Text(g.transform,v,19,TextAnchor.MiddleCenter,Vector2.zero,new Vector2(-16,-10));}
}}