import Fastify from "fastify";
import cors from "@fastify/cors";
import fastifyJwt from "@fastify/jwt";
import websocket from "@fastify/websocket";
import jsonwebtoken from "jsonwebtoken";
import {Pool,PoolClient} from "pg";
import crypto from "node:crypto";
const app=Fastify({logger:true}),pool=new Pool({connectionString:process.env.DATABASE_URL});
const accessSecret=process.env.JWT_ACCESS_SECRET||process.env.JWT_SECRET||"",refreshSecret=process.env.JWT_REFRESH_SECRET||"";
if(accessSecret.length<32||refreshSecret.length<32||accessSecret===refreshSecret)throw new Error("Configure distinct JWT_ACCESS_SECRET and JWT_REFRESH_SECRET values (32+ chars).");
await app.register(cors,{origin:process.env.CORS_ORIGIN||false});await app.register(fastifyJwt,{secret:accessSecret});await app.register(websocket);
type Claims={id:string;type?:string};const sha=(s:string)=>crypto.createHash("sha256").update(s).digest("hex"),scrypt=(p:string,s:string)=>crypto.scryptSync(p,s,64).toString("hex"),access=(id:string)=>app.jwt.sign({id,type:"access"},{expiresIn:"15m"}),refresh=(id:string)=>jsonwebtoken.sign({id,type:"refresh"},refreshSecret,{expiresIn:"30d"}),expiresAt=()=>Math.floor(Date.now()/1000)+900;
async function session(id:string){const accessToken=access(id),refreshToken=refresh(id);await pool.query("INSERT INTO refresh_sessions(token_hash,player_id,expires_at) VALUES($1,$2,now()+interval '30 days')",[sha(refreshToken),id]);return{accessToken,refreshToken,expiresAtUnix:expiresAt(),playerId:id};}
async function auth(req:any,reply:any){try{await req.jwtVerify();const c=req.user as Claims;if(!c.id||c.type!=="access")throw new Error("invalid token");}catch{return reply.code(401).send({error:"unauthorized"});}}
const idOf=(req:any)=>(req.user as Claims).id;
async function reward(c:PoolClient,id:string,cash:number,xp:number,reason:string){const q=await c.query("UPDATE players SET cash=cash+$2,xp=xp+$3,level=GREATEST(1,1+((xp+$3)/1000)::int),updated_at=now() WHERE id=$1 RETURNING cash,bank,xp,level",[id,cash,xp]);if(!q.rowCount)throw new Error("player_not_found");const p=q.rows[0];if(cash>0)await c.query("INSERT INTO ledger(player_id,kind,amount,balance_cash,balance_bank,reason) VALUES($1,'server_reward',$2,$3,$4,$5)",[id,cash,p.cash,p.bank,reason]);await c.query("INSERT INTO audit_log(actor_id,target_id,action,payload) VALUES($1,$1,'reward.granted',$2)",[id,JSON.stringify({reason,cash,xp})]);return p;}
app.get("/health",async()=>({ok:true,service:"corrupt-state-rp-server"}));
app.post("/auth/guest",async(_req,reply)=>{const c=await pool.connect();let tx=false;try{await c.query("BEGIN");tx=true;const id=crypto.randomUUID();await c.query("INSERT INTO players(id) VALUES($1)",[id]);await c.query("COMMIT");tx=false;return await session(id);}catch(e){if(tx)await c.query("ROLLBACK");throw e;}finally{c.release();}});
app.post("/auth/register",async(req:any,reply)=>{const b=req.body as{identifier?:string;password?:string};const identifier=(b.identifier||"").trim(),password=b.password||"",email=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(identifier),phone=/^\+?[0-9]{8,15}$/.test(identifier);if(!identifier||password.length<8)return reply.code(400).send({error:"identifier_and_8_char_password_required"});if(!email&&!phone)return reply.code(400).send({error:"use_email_or_phone"});const salt=crypto.randomBytes(16).toString("hex"),id=crypto.randomUUID();try{await pool.query("INSERT INTO players(id,email,phone,password_hash,password_salt,display_name) VALUES($1,$2,$3,$4,$5,$6)",[id,email?identifier.toLowerCase():null,phone?identifier:null,scrypt(password,salt),salt,identifier]);return await session(id);}catch(e:any){if(e?.code==="23505")return reply.code(409).send({error:"identifier_already_registered"});throw e;}});
app.post("/auth/login",async(req:any,reply)=>{const b=req.body as{identifier?:string;password?:string};if(!b.identifier||!b.password)return reply.code(400).send({error:"credentials_required"});const identifier=b.identifier.includes("@")?b.identifier.toLowerCase():b.identifier,q=await pool.query("SELECT id,password_hash,password_salt FROM players WHERE email=$1 OR phone=$1 LIMIT 1",[identifier]);if(!q.rowCount||!q.rows[0].password_hash||!q.rows[0].password_salt)return reply.code(401).send({error:"invalid_credentials"});const expected=Buffer.from(q.rows[0].password_hash,"hex"),actual=Buffer.from(scrypt(b.password,q.rows[0].password_salt),"hex");if(expected.length!==actual.length||!crypto.timingSafeEqual(expected,actual))return reply.code(401).send({error:"invalid_credentials"});return await session(q.rows[0].id);});
app.post("/auth/refresh",async(req:any,reply)=>{const t=(req.body as{refreshToken?:string})?.refreshToken;if(!t)return reply.code(400).send({error:"refresh_token_required"});let claims:Claims;try{claims=jsonwebtoken.verify(t,refreshSecret) as Claims;}catch{return reply.code(401).send({error:"invalid_refresh_token"});}if(claims.type!=="refresh"||!claims.id)return reply.code(401).send({error:"invalid_refresh_token"});const c=await pool.connect();let tx=false;try{await c.query("BEGIN");tx=true;const found=await c.query("SELECT token_hash FROM refresh_sessions WHERE token_hash=$1 AND player_id=$2 AND revoked_at IS NULL AND expires_at>now() FOR UPDATE",[sha(t),claims.id]);if(!found.rowCount){await c.query("ROLLBACK");tx=false;return reply.code(401).send({error:"refresh_revoked_or_expired"});}await c.query("UPDATE refresh_sessions SET revoked_at=now() WHERE token_hash=$1",[sha(t)]);const accessToken=access(claims.id),refreshToken=refresh(claims.id);await c.query("INSERT INTO refresh_sessions(token_hash,player_id,expires_at) VALUES($1,$2,now()+interval '30 days')",[sha(refreshToken),claims.id]);await c.query("COMMIT");tx=false;return{accessToken,refreshToken,expiresAtUnix:expiresAt(),playerId:claims.id};}catch(e){if(tx)await c.query("ROLLBACK");throw e;}finally{c.release();}});
app.get("/me",{preHandler:[auth]},async(req:any,reply)=>{const q=await pool.query("SELECT id,display_name,cash,bank,xp,level,faction,faction_rank,job_id FROM players WHERE id=$1",[idOf(req)]);if(!q.rowCount)return reply.code(404).send({error:"player_not_found"});return q.rows[0];});
const missions:Record<number,{cash:number;xp:number;reason:string}>={1:{cash:1000,xp:0,reason:"citizen_identity"},2:{cash:500,xp:0,reason:"citizen_bank"},3:{cash:0,xp:500,reason:"citizen_license"},4:{cash:0,xp:0,reason:"citizen_vehicle"},5:{cash:2000,xp:0,reason:"citizen_job"},6:{cash:1500,xp:1000,reason:"citizen_institutions"},7:{cash:2000,xp:0,reason:"citizen_clean_record"},8:{cash:1000,xp:0,reason:"citizen_city"},9:{cash:1500,xp:0,reason:"citizen_social"},10:{cash:10000,xp:0,reason:"citizen_future"}};
async function completeMission(req:any,reply:any,missionId:number){const r=missions[missionId];if(!r)return reply.code(400).send({error:"invalid_mission_id"});const c=await pool.connect();let tx=false;try{await c.query("BEGIN");tx=true;const inserted=await c.query("INSERT INTO mission_completions(player_id,mission_id) VALUES($1,$2) ON CONFLICT DO NOTHING RETURNING mission_id",[idOf(req),missionId]);if(!inserted.rowCount){await c.query("ROLLBACK");tx=false;return reply.code(409).send({error:"mission_already_completed"});}const player=await reward(c,idOf(req),r.cash,r.xp,r.reason);await c.query("COMMIT");tx=false;return{missionId,completed:true,player};}catch(e){if(tx)await c.query("ROLLBACK");throw e;}finally{c.release();}}
app.post("/missions/:missionId/complete",{preHandler:[auth]},async(req:any,reply)=>completeMission(req,reply,Number(req.params.missionId)));
app.post("/missions/complete",{preHandler:[auth]},async(req:any,reply)=>completeMission(req,reply,Number((req.body as any)?.missionId??(req.body as any)?.id)));
const salaries:Record<string,number>={mechanic:800,truck:900,fisherman:700,farmer:600,miner:950,fast_food:650,cleaner:600,taxi:650,bus:750,ride_app:800,media:850,barber:650,tattoo:650};
app.post("/jobs/salary/claim",{preHandler:[auth]},async(req:any,reply)=>{const c=await pool.connect();let tx=false;try{await c.query("BEGIN");tx=true;const q=await c.query("SELECT job_id,salary_claimed_at FROM players WHERE id=$1 FOR UPDATE",[idOf(req)]);if(!q.rowCount){await c.query("ROLLBACK");tx=false;return reply.code(404).send({error:"player_not_found"});}const job=q.rows[0].job_id as string,amount=salaries[job];if(!amount){await c.query("ROLLBACK");tx=false;return reply.code(409).send({error:"no_salary_eligible_job"});}if(q.rows[0].salary_claimed_at&&Date.now()-new Date(q.rows[0].salary_claimed_at).getTime()<300000){await c.query("ROLLBACK");tx=false;return reply.code(429).send({error:"salary_cooldown"});}await c.query("UPDATE players SET salary_claimed_at=now() WHERE id=$1",[idOf(req)]);const player=await reward(c,idOf(req),amount,0,"salary:"+job);await c.query("COMMIT");tx=false;return{amount,player};}catch(e){if(tx)await c.query("ROLLBACK");throw e;}finally{c.release();}});
app.get("/admin/audit",{preHandler:[auth]},async(req:any,reply)=>{const q=await pool.query("SELECT role,permissions FROM admin_roles WHERE player_id=$1",[idOf(req)]);if(!q.rowCount||!["owner","admin","auditor"].includes(q.rows[0].role)||!Array.isArray(q.rows[0].permissions)||!q.rows[0].permissions.includes("audit:read"))return reply.code(403).send({error:"forbidden"});return(await pool.query("SELECT id,actor_id,action,target_id,payload,created_at FROM audit_log ORDER BY created_at DESC LIMIT 100")).rows;});
const sockets=new Set<any>();
function attachSocket(socket:any,req:any){let claims:Claims;try{claims=jsonwebtoken.verify(String(req.query?.token||""),accessSecret) as Claims;if(claims.type!=="access")throw new Error("wrong token");}catch{socket.close(1008,"unauthorized");return;}sockets.add(socket);socket.on("message",(raw:any)=>{try{const m=JSON.parse(raw.toString());if(m.type!=="position"||!Array.isArray(m.position)||m.position.length!==3)return;const p=m.position.map(Number);if(!p.every((n:number)=>Number.isFinite(n)&&Math.abs(n)<100000))return;const event=JSON.stringify({type:"player",id:claims.id,position:p});for(const peer of sockets)if(peer!==socket&&peer.readyState===1)peer.send(event);}catch{/* malformed frame */}});socket.on("close",()=>sockets.delete(socket));}
app.get("/ws/players",{websocket:true},attachSocket);app.get("/",{websocket:true},attachSocket);
await app.listen({port:Number(process.env.PORT||8080),host:"0.0.0.0"});