import Fastify from "fastify";
import cors from "@fastify/cors";
import jwt from "@fastify/jwt";
import {Pool} from "pg";
import crypto from "node:crypto";
const app=Fastify({logger:true});
const pool=new Pool({connectionString:process.env.DATABASE_URL});
await app.register(cors,{origin:process.env.CORS_ORIGIN||false});
await app.register(jwt,{secret:process.env.JWT_SECRET||"development-only-secret"});
type AuthUser={id:string};
const hash=(v:string)=>crypto.createHash("sha256").update(v).digest("hex");
const token=(id:string)=>app.jwt.sign({id},{expiresIn:"15m"});
const refresh=(id:string)=>app.jwt.sign({id,type:"refresh"},{expiresIn:"30d"});
app.get("/health",async()=>({ok:true,service:"corrupt-state-rp-server"}));
app.post("/auth/guest",async()=>{const id=crypto.randomUUID();const q=await pool.query("INSERT INTO players(id) VALUES($1) RETURNING id,display_name,cash,bank,xp,level,faction,faction_rank",[id]);return {accessToken:token(id),refreshToken:refresh(id),player:q.rows[0]};});
app.post("/auth/login",async(req,reply)=>{const b=req.body as {identifier?:string,password?:string};if(!b.identifier||!b.password)return reply.code(400).send({error:"credentials_required"});const q=await pool.query("SELECT * FROM players WHERE email=$1 OR phone=$1 LIMIT 1",[b.identifier]);if(!q.rowCount||q.rows[0].password_hash!==hash(b.password))return reply.code(401).send({error:"invalid_credentials"});const p=q.rows[0];return {accessToken:token(p.id),refreshToken:refresh(p.id),player:p};});
app.get("/me",{preHandler:[async(req)=>{await req.jwtVerify()}]},async(req)=>{const id=(req.user as AuthUser).id;const q=await pool.query("SELECT id,display_name,cash,bank,xp,level,faction,faction_rank FROM players WHERE id=$1",[id]);return q.rows[0]||null;});
app.post("/economy/transaction",{preHandler:[async(req)=>{await req.jwtVerify()}]},async(req,reply)=>{const id=(req.user as AuthUser).id;const b=req.body as {amount?:number,reason?:string,kind?:string};const amount=Math.trunc(Number(b.amount));if(!Number.isSafeInteger(amount)||!b.reason||Math.abs(amount)>100000000)return reply.code(400).send({error:"invalid_transaction"});const c=await pool.connect();try{await c.query("BEGIN");const p=(await c.query("SELECT cash,bank FROM players WHERE id=$1 FOR UPDATE",[id])).rows[0];if(!p)return reply.code(404).send({error:"player_not_found"});const nextCash=Number(p.cash)+amount;if(nextCash<0)return reply.code(409).send({error:"insufficient_cash"});await c.query("UPDATE players SET cash=$1,updated_at=now() WHERE id=$2",[nextCash,id]);await c.query("INSERT INTO ledger(player_id,kind,amount,balance_cash,balance_bank,reason) VALUES($1,$2,$3,$4,$5,$6)",[id,b.kind||"gameplay",amount,nextCash,p.bank,b.reason]);await c.query("INSERT INTO audit_log(actor_id,action,target_id,payload) VALUES($1,$2,$3,$4)",[id,"economy.transaction",id,JSON.stringify({amount,reason:b.reason})]);await c.query("COMMIT");return {cash:nextCash,bank:Number(p.bank)};}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}});
app.get("/admin/audit",{preHandler:[async(req)=>{await req.jwtVerify()}]},async(req,reply)=>{const id=(req.user as AuthUser).id;const p=await pool.query("SELECT faction,faction_rank FROM players WHERE id=$1",[id]);if(!p.rowCount||p.rows[0].faction_rank===null)return reply.code(403).send({error:"forbidden"});return (await pool.query("SELECT id,actor_id,action,target_id,payload,created_at FROM audit_log ORDER BY created_at DESC LIMIT 100")).rows;});
await app.listen({port:Number(process.env.PORT||8080),host:"0.0.0.0"});