using System;using System.Collections.Concurrent;using System.Collections.Generic;using System.Net.WebSockets;using System.Text;using System.Threading;using System.Threading.Tasks;using UnityEngine;
namespace CorruptStateRP {
public sealed class PlayerRealtimeClient:MonoBehaviour {
 ClientWebSocket socket;CancellationTokenSource cancel;readonly ConcurrentQueue<string> incoming=new ConcurrentQueue<string>();readonly Dictionary<string,Transform> remotePlayers=new Dictionary<string,Transform>();public event Action<string> MessageReceived;
 public async void Connect(string baseUrl,string accessToken){Disconnect();if(string.IsNullOrWhiteSpace(baseUrl)||string.IsNullOrWhiteSpace(accessToken))return;try{var uri=new Uri(baseUrl.Replace("https://","wss://").Replace("http://","ws://").TrimEnd('/')+"/?token="+Uri.EscapeDataString(accessToken));socket=new ClientWebSocket();cancel=new CancellationTokenSource();await socket.ConnectAsync(uri,cancel.Token);_=ReceiveLoop(socket,cancel.Token);}catch(Exception e){Debug.LogWarning("Realtime WebSocket connection failed: "+e.Message);Disconnect();}}
 async Task ReceiveLoop(ClientWebSocket ws,CancellationToken token){var buffer=new byte[8192];try{while(ws.State==WebSocketState.Open&&!token.IsCancellationRequested){var result=await ws.ReceiveAsync(new ArraySegment<byte>(buffer),token);if(result.MessageType==WebSocketMessageType.Close)break;incoming.Enqueue(Encoding.UTF8.GetString(buffer,0,result.Count));}}catch(Exception e){if(!token.IsCancellationRequested)Debug.LogWarning("WebSocket receive ended: "+e.Message);}}
 public async void SendPosition(Vector3 position){if(socket==null||socket.State!=WebSocketState.Open)return;var json=JsonUtility.ToJson(new PositionMessage{type="position",position=new[]{position.x,position.y,position.z}});var data=Encoding.UTF8.GetBytes(json);try{await socket.SendAsync(new ArraySegment<byte>(data),WebSocketMessageType.Text,true,cancel.Token);}catch(Exception e){Debug.LogWarning("WebSocket send failed: "+e.Message);}}
 void Update(){while(incoming.TryDequeue(out var msg)){MessageReceived?.Invoke(msg);ApplyRemotePosition(msg);}}
 void ApplyRemotePosition(string json){try{var m=JsonUtility.FromJson<RemotePositionMessage>(json);if(m==null||m.type!="player"||string.IsNullOrWhiteSpace(m.id)||m.position==null||m.position.Length!=3)return;if(!remotePlayers.TryGetValue(m.id,out var t)){var go=GameObject.CreatePrimitive(PrimitiveType.Capsule);go.name="RemotePlayer_"+m.id;t=go.transform;remotePlayers[m.id]=t;var r=go.GetComponent<Renderer>();var shader=Shader.Find("Universal Render Pipeline/Lit")??Shader.Find("Standard");var mat=new Material(shader);mat.color=new Color(.18f,.62f,.82f);r.material=mat;}t.position=new Vector3(m.position[0],m.position[1],m.position[2]);}catch(Exception e){Debug.LogWarning("Invalid realtime player message: "+e.Message);}}
 public void Disconnect(){try{cancel?.Cancel();socket?.Abort();socket?.Dispose();cancel?.Dispose();}catch{}socket=null;cancel=null;foreach(var t in remotePlayers.Values)if(t!=null)Destroy(t.gameObject);remotePlayers.Clear();}
 void OnDestroy(){Disconnect();}
 [Serializable]class PositionMessage{public string type;public float[] position;}[Serializable]class RemotePositionMessage{public string type;public string id;public float[] position;}
}}