using System;using System.Collections.Concurrent;using System.Net.WebSockets;using System.Text;using System.Threading;using System.Threading.Tasks;using UnityEngine;
namespace CorruptStateRP {
public sealed class PlayerRealtimeClient:MonoBehaviour {
 ClientWebSocket socket;CancellationTokenSource cancel;readonly ConcurrentQueue<string> incoming=new ConcurrentQueue<string>();public event Action<string> MessageReceived;
 public async void Connect(string baseUrl,string accessToken){Disconnect();if(string.IsNullOrWhiteSpace(baseUrl)||string.IsNullOrWhiteSpace(accessToken))return;try{var uri=new Uri(baseUrl.Replace("https://","wss://").Replace("http://","ws://").TrimEnd('/')+"/?token="+Uri.EscapeDataString(accessToken));socket=new ClientWebSocket();cancel=new CancellationTokenSource();await socket.ConnectAsync(uri,cancel.Token);_=ReceiveLoop(socket,cancel.Token);}catch(Exception e){Debug.LogWarning("Realtime WebSocket connection failed: "+e.Message);Disconnect();}}
 async Task ReceiveLoop(ClientWebSocket ws,CancellationToken token){var buffer=new byte[8192];try{while(ws.State==WebSocketState.Open&&!token.IsCancellationRequested){var result=await ws.ReceiveAsync(new ArraySegment<byte>(buffer),token);if(result.MessageType==WebSocketMessageType.Close)break;incoming.Enqueue(Encoding.UTF8.GetString(buffer,0,result.Count));}}catch(Exception e){if(!token.IsCancellationRequested)Debug.LogWarning("WebSocket receive ended: "+e.Message);}}
 public async void SendPosition(Vector3 position){if(socket==null||socket.State!=WebSocketState.Open)return;var json=JsonUtility.ToJson(new PositionMessage{type="position",position=new[]{position.x,position.y,position.z}});var data=Encoding.UTF8.GetBytes(json);try{await socket.SendAsync(new ArraySegment<byte>(data),WebSocketMessageType.Text,true,cancel.Token);}catch(Exception e){Debug.LogWarning("WebSocket send failed: "+e.Message);}}
 void Update(){while(incoming.TryDequeue(out var msg))MessageReceived?.Invoke(msg);}
 public void Disconnect(){try{cancel?.Cancel();socket?.Abort();socket?.Dispose();cancel?.Dispose();}catch{}socket=null;cancel=null;}
 void OnDestroy(){Disconnect();}
 [Serializable]class PositionMessage{public string type;public float[] position;}
}}