using System;
using UnityEngine;

namespace CorruptStateRP {
public sealed class WorldBuilder:MonoBehaviour {
 public const float CitySize=600f; const float Cell=10f, RoadSpacing=40f; readonly System.Random rng=new(20261005);
 readonly string[] buildings={"Generated3D/commercial_a","Generated3D/commercial_b","Generated3D/skyscraper_a","Generated3D/skyscraper_b","Generated3D/skyscraper_c","Generated3D/suburban_a","Generated3D/suburban_b","Generated3D/suburban_c"};
 readonly (string,Vector3,string)[] landmarks={
  ("مركز الشرطة",new(-65,0,-65),"Generated3D/commercial_a"),("المستشفى",new(65,0,-65),"Generated3D/commercial_b"),
  ("البنك المركزي",new(-65,0,65),"Generated3D/skyscraper_a"),("دار الحكومة",new(65,0,65),"Generated3D/skyscraper_b"),
  ("المحكمة",new(-105,0,0),"Generated3D/suburban_a"),("السجن",new(105,0,0),"Generated3D/suburban_b"),
  ("الكراج",new(0,0,-105),"Generated3D/commercial_a"),("السوق",new(0,0,105),"Generated3D/commercial_b"),
  ("منطقة العصابات",new(-105,0,105),"Generated3D/suburban_c"),("الميناء",new(105,0,105),"Generated3D/commercial_a")};
 public void Build(){Environment();GroundAndRoads();Buildings();Landmarks();Life();}
 void Environment(){RenderSettings.ambientLight=new(.72f,.78f,.83f);RenderSettings.fog=true;RenderSettings.fogColor=new(.43f,.51f,.57f);RenderSettings.fogDensity=.004f;var s=new GameObject("Sun").AddComponent<Light>();s.type=LightType.Directional;s.intensity=1.7f;s.shadows=LightShadows.Soft;s.transform.rotation=Quaternion.Euler(52,-28,0);}
 void GroundAndRoads(){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name="CityGround";g.transform.position=new(0,-.55f,0);g.transform.localScale=new(CitySize,1,CitySize);g.GetComponent<Renderer>().material=Mat(new(.20f,.25f,.29f));for(int x=-30;x<=30;x++)for(int z=-30;z<=30;z++){if(!(Mathf.Abs(x)<=1||Mathf.Abs(z)<=1||x%4==0||z%4==0))continue;var r=GameObject.CreatePrimitive(PrimitiveType.Cube);r.name="Road";r.transform.position=new(x*Cell,0,z*Cell);r.transform.localScale=new(Cell,.12f,Cell);r.GetComponent<Renderer>().material=Mat(new(.07f,.09f,.11f));}BuildMainRoads();}
 void Buildings(){for(int x=-28;x<=28;x+=2)for(int z=-28;z<=28;z+=2){if(Mathf.Abs(x)<=1||Mathf.Abs(z)<=1||x%4==0||z%4==0)continue;var p=new Vector3(x*Cell,0,z*Cell);var go=Spawn(buildings[rng.Next(buildings.Length)],p,Mathf.Abs(x)<12&&Mathf.Abs(z)<12?1.25f:1.05f,"Building");if(go==null)BuildDetailedBuilding(p,1f);}}
 void BuildMainRoads(){var sidewalk=Mat(new(.30f,.31f,.31f));var curb=Mat(new(.16f,.17f,.18f));foreach(float z in new float[]{-20,20}){var s=GameObject.CreatePrimitive(PrimitiveType.Cube);s.name="CentralSidewalk";s.transform.position=new(0,.07f,z);s.transform.localScale=new(CitySize,.18f,3.5f);s.GetComponent<Renderer>().material=sidewalk;}foreach(float x in new float[]{-20,20}){var s=GameObject.CreatePrimitive(PrimitiveType.Cube);s.name="CentralSidewalk";s.transform.position=new(x,.07f,0);s.transform.localScale=new(3.5f,.18f,CitySize);s.GetComponent<Renderer>().material=sidewalk;}for(int i=-13;i<=13;i++){StreetLight(new(i*40,.1f,27),Quaternion.identity,curb);StreetLight(new(i*40,.1f,-27),Quaternion.identity,curb);StreetLight(new(27,.1f,i*40),Quaternion.Euler(0,90,0),curb);StreetLight(new(-27,.1f,i*40),Quaternion.Euler(0,90,0),curb);}} 
void StreetLight(Vector3 p,Quaternion rot,Material mat){var root=new GameObject("StreetLight");root.transform.SetPositionAndRotation(p,rot);var pole=GameObject.CreatePrimitive(PrimitiveType.Cylinder);pole.transform.SetParent(root.transform,false);pole.transform.localPosition=Vector3.up*3.1f;pole.transform.localScale=new(.09f,3.1f,.09f);pole.GetComponent<Renderer>().material=mat;var lamp=GameObject.CreatePrimitive(PrimitiveType.Sphere);lamp.transform.SetParent(root.transform,false);lamp.transform.localPosition=new Vector3(0,6.1f,0);lamp.transform.localScale=Vector3.one*.35f;var m=Mat(new(.95f,.82f,.55f));lamp.GetComponent<Renderer>().material=m;var l=lamp.AddComponent<Light>();l.type=LightType.Point;l.range=8;l.intensity=.7f;} 
void BuildDetailedBuilding(Vector3 p,float scale){var root=new GameObject("CityBuilding");root.transform.position=p;float h=rng.Next(2,7)*3.2f;float w=rng.Next(2,4)*4.5f;float d=rng.Next(2,4)*4.5f;var body=GameObject.CreatePrimitive(PrimitiveType.Cube);body.transform.SetParent(root.transform,false);body.transform.localPosition=Vector3.up*h*.5f;body.transform.localScale=new Vector3(w,h,d);body.GetComponent<Renderer>().material=Mat(new Color(.16f,.19f,.23f));for(int floor=0;floor<Mathf.Max(1,Mathf.FloorToInt(h/3.2f));floor++){for(int side=-1;side<=1;side+=2){var win=GameObject.CreatePrimitive(PrimitiveType.Cube);win.transform.SetParent(root.transform,false);win.transform.localPosition=new Vector3(side*(w*.5f+.03f),1.0f+floor*3.2f,0);win.transform.localScale=new Vector3(.08f,1.35f,d*.65f);win.GetComponent<Renderer>().material=Mat(new Color(.35f,.48f,.58f));}}var roof=GameObject.CreatePrimitive(PrimitiveType.Cube);roof.transform.SetParent(root.transform,false);roof.transform.localPosition=Vector3.up*(h+.18f);roof.transform.localScale=new Vector3(w+.3f,.35f,d+.3f);roof.GetComponent<Renderer>().material=Mat(new Color(.08f,.09f,.11f));}
 void Landmarks(){foreach(var l in landmarks){var go=Spawn(l.Item3,l.Item2,1.35f,l.Item1);if(go==null){go=GameObject.CreatePrimitive(PrimitiveType.Cube);go.transform.position=l.Item2;}var t=new GameObject("Label").AddComponent<TextMesh>();t.text=l.Item1;t.fontSize=48;t.characterSize=.08f;t.anchor=TextAnchor.MiddleCenter;t.transform.SetParent(go.transform,false);t.transform.localPosition=new(0,10,0);}}
 void Life(){for(int i=0;i<80;i++){float x=(float)rng.NextDouble()*570-285,z=(float)rng.NextDouble()*570-285;if(Mathf.Abs(x)<125&&Mathf.Abs(z)<125)continue;if(Mathf.Abs(x%RoadSpacing)<8||Mathf.Abs(z%RoadSpacing)<8)continue;Tree(new(x,0,z),.8f+(float)rng.NextDouble()*.5f);}foreach(var p in new Vector3[]{new Vector3(-210,0,-80),new Vector3(210,0,80),new Vector3(-205,0,120),new Vector3(205,0,-120)})for(int j=0;j<9;j++)Tree(p+new Vector3((float)rng.NextDouble()*44-22,0,(float)rng.NextDouble()*36-18),.9f);var cars=new[]{"Generated3D/sedan","Generated3D/suv","Generated3D/taxi"};for(int i=0;i<34;i++){var p=new Vector3((float)rng.NextDouble()*500-250,.2f,(float)rng.NextDouble()*500-250);if(Mathf.Abs(p.x%RoadSpacing)>10&&Mathf.Abs(p.z%RoadSpacing)>10)continue;Spawn(cars[rng.Next(cars.Length)],p,1,"ParkedCar");}}
 void Tree(Vector3 p,float s){var root=new GameObject("StreetTree");root.transform.SetPositionAndRotation(p,Quaternion.identity);root.transform.localScale=Vector3.one*s;var tr=GameObject.CreatePrimitive(PrimitiveType.Cylinder);tr.transform.SetParent(root.transform,false);tr.transform.localPosition=Vector3.up*1.2f;tr.transform.localScale=new(.22f,1.2f,.22f);tr.GetComponent<Renderer>().material=Mat(new(.36f,.23f,.15f));var cr=GameObject.CreatePrimitive(PrimitiveType.Sphere);cr.transform.SetParent(root.transform,false);cr.transform.localPosition=Vector3.up*3;cr.transform.localScale=Vector3.one*2.3f;cr.GetComponent<Renderer>().material=Mat(new(.18f,.42f,.23f));}
 GameObject Spawn(string path,Vector3 p,float s,string n){var prefab=Resources.Load<GameObject>(path);if(prefab==null)return null;var go=Instantiate(prefab,p,Quaternion.identity);go.name=n;go.transform.localScale*=s;return go;}
 static Material Mat(Color c){var sh=Shader.Find("Universal Render Pipeline/Lit")??Shader.Find("Standard");var m=new Material(sh);m.color=c;m.SetFloat("_Smoothness",.15f);return m;}
}
}
