using UnityEngine;
using UnityEngine.UI;
using CorruptStateRP.Auth;
using CorruptStateRP.UI;

namespace CorruptStateRP.Onboarding {
public sealed class OnboardingScreen : MonoBehaviour {
 public enum Mode { Splash, Login, Lobby }
 [SerializeField] Mode mode; Font font;
 void Awake(){font=Resources.GetBuiltinResource<Font>("Arial.ttf");Build();}
 Text Label(Transform p,string value,int size,TextAnchor align){var go=new GameObject("Text");go.transform.SetParent(p,false);var t=go.AddComponent<Text>();t.font=font;t.text=value;t.fontSize=size;t.alignment=align;t.color=Color.white;t.rectTransform.sizeDelta=new Vector2(1500,100);return t;}
 Button Button(Transform p,string value,UnityEngine.Events.UnityAction click){var go=new GameObject(value);go.transform.SetParent(p,false);var img=go.AddComponent<Image>();img.color=new Color(.12f,.12f,.14f,1);var b=go.AddComponent<Button>();b.targetGraphic=img;b.onClick.AddListener(click);Label(go.transform,value,32,TextAnchor.MiddleCenter);go.GetComponent<RectTransform>().sizeDelta=new Vector2(900,110);return b;}
 void Build(){var canvas=new GameObject("Canvas").AddComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;canvas.gameObject.AddComponent<CanvasScaler>();canvas.gameObject.AddComponent<GraphicRaycaster>();canvas.gameObject.AddComponent<ResponsiveCanvas>();var safe=new GameObject("SafeArea",typeof(RectTransform),typeof(SafeAreaPanel));safe.transform.SetParent(canvas.transform,false);var root=safe.GetComponent<RectTransform>();root.anchorMin=Vector2.zero;root.anchorMax=Vector2.one;root.offsetMin=root.offsetMax=Vector2.zero;var bg=safe.gameObject.AddComponent<Image>();bg.color=new Color(.025f,.025f,.035f,1);bg.raycastTarget=false;var panel=new GameObject("Content");panel.transform.SetParent(safe.transform,false);var pr=panel.AddComponent<RectTransform>();pr.anchorMin=new Vector2(.1f,.12f);pr.anchorMax=new Vector2(.9f,.88f);pr.offsetMin=pr.offsetMax=Vector2.zero;var layout=panel.AddComponent<VerticalLayoutGroup>();layout.spacing=28;layout.childAlignment=TextAnchor.MiddleCenter;layout.childControlHeight=false;layout.childControlWidth=true;if(mode==Mode.Splash){Label(panel.transform,"CORRUPT STATE RP",64,TextAnchor.MiddleCenter);Label(panel.transform,"لكل مدينة قصة... ولكل قصة بداية.",34,TextAnchor.MiddleCenter);return;}if(mode==Mode.Login){Label(panel.transform,"تسجيل الدخول",58,TextAnchor.MiddleCenter);panel.gameObject.AddComponent<LoginScreenInputs>().Build(panel.transform);return;}if(mode==Mode.Lobby)return;}
}
sealed class LoginScreenInputs:MonoBehaviour{
 public void Build(Transform p){var email=Field(p,"البريد الإلكتروني أو الهاتف");var pass=Field(p,"كلمة المرور");var b=new GameObject("LoginButton");b.transform.SetParent(p,false);var img=b.AddComponent<Image>();img.color=new Color(.65f,.05f,.05f);var btn=b.AddComponent<Button>();btn.targetGraphic=img;var txt=b.AddComponent<Text>();txt.font=Resources.GetBuiltinResource<Font>("Arial.ttf");txt.text="تسجيل الدخول";txt.fontSize=32;txt.alignment=TextAnchor.MiddleCenter;txt.color=Color.white;b.GetComponent<RectTransform>().sizeDelta=new Vector2(900,110);btn.onClick.AddListener(()=>Login(email.text,pass.text));}
 InputField Field(Transform p,string hint){var go=new GameObject(hint);go.transform.SetParent(p,false);var img=go.AddComponent<Image>();img.color=new Color(.1f,.1f,.12f,1);var f=go.AddComponent<InputField>();f.targetGraphic=img;f.textComponent=go.AddComponent<Text>();f.textComponent.font=Resources.GetBuiltinResource<Font>("Arial.ttf");f.textComponent.fontSize=28;f.textComponent.color=Color.white;var ph=new GameObject("Placeholder").AddComponent<Text>();ph.transform.SetParent(go.transform,false);ph.font=Resources.GetBuiltinResource<Font>("Arial.ttf");ph.text=hint;ph.fontSize=26;ph.color=new Color(1,1,1,.45f);f.placeholder=ph;go.GetComponent<RectTransform>().sizeDelta=new Vector2(900,100);return f;}
 void Login(string id,string pw){var auth=FindFirstObjectByType<AuthClient>();if(auth==null){var go=new GameObject("AuthClient");auth=go.AddComponent<AuthClient>();}StartCoroutine(auth.Login(id,pw,(ok,error)=>{if(ok)UnityEngine.SceneManagement.SceneManager.LoadScene("LobbyScene");else Debug.LogWarning(error);}));}
}
}