using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;using CorruptStateRP.Auth;using CorruptStateRP.UI;
namespace CorruptStateRP.Onboarding {
public sealed class OnboardingScreen:MonoBehaviour {
 public enum Mode{Splash,Login,Lobby}[SerializeField] Mode mode;Font font;
 void Awake(){font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");if(FindFirstObjectByType<EventSystem>()==null){var e=new GameObject("EventSystem");e.AddComponent<EventSystem>();e.AddComponent<StandaloneInputModule>();}Build();}
 Text Label(Transform p,string v,int n,TextAnchor a){var g=new GameObject("Text");g.transform.SetParent(p,false);var t=g.AddComponent<Text>();t.font=font;t.text=ArabicFixer.Fix(v);t.fontSize=n;t.alignment=a;t.color=Color.white;t.rectTransform.sizeDelta=new Vector2(1500,100);return t;}
 void Build(){var c=new GameObject("Canvas").AddComponent<Canvas>();c.renderMode=RenderMode.ScreenSpaceOverlay;var sc=c.gameObject.AddComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1920,1080);sc.matchWidthOrHeight=.5f;c.gameObject.AddComponent<GraphicRaycaster>();c.gameObject.AddComponent<ResponsiveCanvas>();var safe=new GameObject("SafeArea",typeof(RectTransform),typeof(SafeAreaPanel));safe.transform.SetParent(c.transform,false);var sr=safe.GetComponent<RectTransform>();sr.anchorMin=Vector2.zero;sr.anchorMax=Vector2.one;sr.offsetMin=sr.offsetMax=Vector2.zero;safe.AddComponent<Image>().color=new Color(.02f,.025f,.035f,1);var panel=new GameObject("Content");panel.transform.SetParent(safe.transform,false);var pr=panel.AddComponent<RectTransform>();pr.anchorMin=new Vector2(.12f,.08f);pr.anchorMax=new Vector2(.88f,.92f);pr.offsetMin=pr.offsetMax=Vector2.zero;var layout=panel.AddComponent<VerticalLayoutGroup>();layout.spacing=18;layout.childAlignment=TextAnchor.MiddleCenter;layout.childControlHeight=false;layout.childControlWidth=true;if(mode==Mode.Splash){Label(panel.transform,"CORRUPT STATE RP",64,TextAnchor.MiddleCenter);Label(panel.transform,"لكل مدينة قصة... ولكل قصة بداية.",34,TextAnchor.MiddleCenter);}else if(mode==Mode.Login){Label(panel.transform,"تسجيل الدخول",56,TextAnchor.MiddleCenter);panel.AddComponent<LoginScreenInputs>().Build(panel.transform);}}
}
sealed class LoginScreenInputs:MonoBehaviour {
 InputField endpoint;
 public void Build(Transform p){endpoint=Field(p,"عنوان الخادم https://api.example.com",false);endpoint.text=PlayerPrefs.GetString("CSRP_API_URL","");var id=Field(p,"البريد الإلكتروني أو الهاتف",false);var pw=Field(p,"كلمة المرور (8 أحرف على الأقل)",true);Button(p,"حفظ عنوان الخادم",()=>{var a=GetAuth();a.Configure(endpoint.text);});Button(p,"تسجيل الدخول",()=>Login(id.text,pw.text));Button(p,"إنشاء حساب",()=>Register(id.text,pw.text));Button(p,"الدخول كضيف",()=>Guest());}
 InputField Field(Transform p,string hint,bool password){var g=new GameObject("Field");g.transform.SetParent(p,false);g.AddComponent<RectTransform>().sizeDelta=new Vector2(900,95);g.AddComponent<Image>().color=new Color(.09f,.1f,.13f,1);var f=g.AddComponent<InputField>();var child=new GameObject("Text");child.transform.SetParent(g.transform,false);var t=child.AddComponent<Text>();t.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");t.fontSize=28;t.color=Color.white;t.alignment=TextAnchor.MiddleRight;t.supportRichText=false;var tr=t.rectTransform;tr.anchorMin=Vector2.zero;tr.anchorMax=Vector2.one;tr.offsetMin=new Vector2(16,8);tr.offsetMax=new Vector2(-16,-8);f.textComponent=t;f.contentType=password?InputField.ContentType.Password:InputField.ContentType.Standard;var ph=new GameObject("Placeholder");ph.transform.SetParent(g.transform,false);var pt=ph.AddComponent<Text>();pt.font=t.font;pt.text=ArabicFixer.Fix(hint);pt.fontSize=24;pt.color=new Color(1,1,1,.45f);pt.alignment=TextAnchor.MiddleRight;pt.raycastTarget=false;var rr=pt.rectTransform;rr.anchorMin=Vector2.zero;rr.anchorMax=Vector2.one;rr.offsetMin=new Vector2(16,8);rr.offsetMax=new Vector2(-16,-8);f.placeholder=pt;return f;}
 void Button(Transform p,string label,UnityEngine.Events.UnityAction a){var g=new GameObject("Button");g.transform.SetParent(p,false);g.AddComponent<RectTransform>().sizeDelta=new Vector2(900,90);var im=g.AddComponent<Image>();im.color=new Color(.12f,.12f,.15f,1);var b=g.AddComponent<Button>();b.targetGraphic=im;b.onClick.AddListener(a);var child=new GameObject("Text");child.transform.SetParent(g.transform,false);var t=child.AddComponent<Text>();t.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");t.text=ArabicFixer.Fix(label);t.fontSize=28;t.alignment=TextAnchor.MiddleCenter;t.color=Color.white;t.raycastTarget=false;var r=t.rectTransform;r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;}
 AuthClient GetAuth(){var a=FindFirstObjectByType<AuthClient>()??new GameObject("AuthClient").AddComponent<AuthClient>();if(!string.IsNullOrWhiteSpace(endpoint.text))a.Configure(endpoint.text);return a;}
 void AfterAuth(bool ok,string err){if(!ok){Debug.LogWarning("Authentication failed: "+err);return;}var a=GetAuth();StartCoroutine(a.GetMe((json,error)=>{if(error!=null){Debug.LogWarning("Server /me failed: "+error);return;}Debug.Log("Authenticated player state received from /me.");UnityEngine.SceneManagement.SceneManager.LoadScene("LobbyScene");}));}
 void Login(string id,string pw){if(string.IsNullOrWhiteSpace(endpoint.text)){Debug.LogWarning("Set the server URL first.");return;}StartCoroutine(GetAuth().Login(id,pw,AfterAuth));}
 void Register(string id,string pw){if(string.IsNullOrWhiteSpace(endpoint.text)){Debug.LogWarning("Set the server URL first.");return;}StartCoroutine(GetAuth().Register(id,pw,AfterAuth));}
 void Guest(){if(string.IsNullOrWhiteSpace(endpoint.text)){Debug.LogWarning("Set the server URL first.");return;}StartCoroutine(GetAuth().Guest(AfterAuth));}
}}