using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using CorruptStateRP.Auth;
using CorruptStateRP.UI;
namespace CorruptStateRP.Onboarding{
public sealed class OnboardingScreen:MonoBehaviour{
 public enum Mode{Splash,Login,Lobby}
 [SerializeField] Mode mode; Font font;
 void Awake(){font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");EnsureEventSystem();Build();}
 void EnsureEventSystem(){if(FindFirstObjectByType<EventSystem>()==null){var e=new GameObject("EventSystem");e.AddComponent<EventSystem>();e.AddComponent<StandaloneInputModule>();}}
 Text Label(Transform p,string value,int size,TextAnchor align){var go=new GameObject("Text");go.transform.SetParent(p,false);var t=go.AddComponent<Text>();t.font=font;t.text=ArabicFixer.Fix(value);t.fontSize=size;t.alignment=align;t.color=Color.white;t.rectTransform.sizeDelta=new Vector2(1500,100);return t;}
 Button Button(Transform p,string value,UnityEngine.Events.UnityAction click){var go=new GameObject("Button");go.transform.SetParent(p,false);var img=go.AddComponent<Image>();img.color=new Color(.12f,.12f,.15f,1);var b=go.AddComponent<Button>();b.targetGraphic=img;b.onClick.AddListener(click);Label(go.transform,value,30,TextAnchor.MiddleCenter);go.GetComponent<RectTransform>().sizeDelta=new Vector2(900,105);return b;}
 void Build(){var canvas=new GameObject("Canvas").AddComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;var scaler=canvas.gameObject.AddComponent<CanvasScaler>();scaler.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new Vector2(1920,1080);scaler.matchWidthOrHeight=.5f;canvas.gameObject.AddComponent<GraphicRaycaster>();canvas.gameObject.AddComponent<ResponsiveCanvas>();var safe=new GameObject("SafeArea",typeof(RectTransform),typeof(SafeAreaPanel));safe.transform.SetParent(canvas.transform,false);var root=safe.GetComponent<RectTransform>();root.anchorMin=Vector2.zero;root.anchorMax=Vector2.one;root.offsetMin=root.offsetMax=Vector2.zero;safe.AddComponent<Image>().color=new Color(.02f,.025f,.035f,1);var panel=new GameObject("Content");panel.transform.SetParent(safe.transform,false);var pr=panel.AddComponent<RectTransform>();pr.anchorMin=new Vector2(.12f,.08f);pr.anchorMax=new Vector2(.88f,.92f);pr.offsetMin=pr.offsetMax=Vector2.zero;var layout=panel.AddComponent<VerticalLayoutGroup>();layout.spacing=18;layout.childAlignment=TextAnchor.MiddleCenter;layout.childControlHeight=false;layout.childControlWidth=true;if(mode==Mode.Splash){Label(panel.transform,"CORRUPT STATE RP",64,TextAnchor.MiddleCenter);Label(panel.transform,"لكل مدينة قصة... ولكل قصة بداية.",34,TextAnchor.MiddleCenter);return;}if(mode==Mode.Login){Label(panel.transform,"تسجيل الدخول",56,TextAnchor.MiddleCenter);panel.gameObject.AddComponent<LoginScreenInputs>().Build(panel.transform);return;}}
}
sealed class LoginScreenInputs:MonoBehaviour{
 public void Build(Transform p){var id=Field(p,"البريد الإلكتروني أو الهاتف");var pass=Field(p,"كلمة المرور");Button(p,"تسجيل الدخول",()=>Login(id.text,pass.text));Button(p,"الدخول كضيف",()=>Guest());Button(p,"Facebook",()=>Debug.Log("Facebook provider requires configured OAuth credentials."));Button(p,"تسجيل برقم الهاتف",()=>Debug.Log("Phone provider requires configured SMS credentials."));}
 InputField Field(Transform p,string hint){var go=new GameObject("Input");go.transform.SetParent(p,false);go.AddComponent<Image>().color=new Color(.09f,.1f,.13f,1);var f=go.AddComponent<InputField>();var txt=go.AddComponent<Text>();txt.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");txt.fontSize=28;txt.color=Color.white;txt.alignment=TextAnchor.MiddleRight;f.textComponent=txt;var ph=new GameObject("Placeholder");ph.transform.SetParent(go.transform,false);var pt=ph.AddComponent<Text>();pt.font=txt.font;pt.text=ArabicFixer.Fix(hint);pt.fontSize=26;pt.color=new Color(1,1,1,.45f);pt.alignment=TextAnchor.MiddleRight;f.placeholder=pt;go.GetComponent<RectTransform>().sizeDelta=new Vector2(900,95);return f;}
 Button Button(Transform p,string label,UnityEngine.Events.UnityAction a){var go=new GameObject("Action");go.transform.SetParent(p,false);go.AddComponent<Image>().color=new Color(.12f,.12f,.15f,1);var b=go.AddComponent<Button>();b.targetGraphic=go.GetComponent<Image>();b.onClick.AddListener(a);var t=go.AddComponent<Text>();t.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");t.text=ArabicFixer.Fix(label);t.fontSize=28;t.alignment=TextAnchor.MiddleCenter;t.color=Color.white;go.GetComponent<RectTransform>().sizeDelta=new Vector2(900,90);return b;}
 void Login(string id,string pw){var auth=FindFirstObjectByType<AuthClient>()??new GameObject("AuthClient").AddComponent<AuthClient>();StartCoroutine(auth.Login(id,pw,(ok,error)=>{if(ok)UnityEngine.SceneManagement.SceneManager.LoadScene("LobbyScene");else Debug.LogWarning(error);}));}
 void Guest(){var auth=FindFirstObjectByType<AuthClient>()??new GameObject("AuthClient").AddComponent<AuthClient>();StartCoroutine(auth.Guest((ok,error)=>{if(ok)UnityEngine.SceneManagement.SceneManager.LoadScene("LobbyScene");else Debug.LogWarning(error);}));}
}}
